<?php 
$ronda=$resultado1['revision'];
$nivel=$resultado1['niveles'];
$diar=$resultado1['accdiarias'];
$mant=$resultado1['accmantenimiento'];
$prod=$resultado1['productos'];
$inci=$resultado1['incidencia'];
$mens=$resultado1['mensaje'];
$alar=$resultado1['alarma'];
$trab=$resultado1['trabajo'];
$sini=$resultado1['siniestro'];
$acce=$resultado1['control'];
$medi=$resultado1['mediciones'];
$ruta=$resultado1['ruta'];
$enva=$resultado1['envases'];
$incimas=$resultado1['incidenciasplus'];
$segui=$resultado1['seguimiento'];
$total=$ronda.';'.$nivel.';'.$diar.';'.$mant.';'.$prod.';'.$inci.';'.$mens.';'.$alar.';'.$trab.';'.$sini.';'.$acce.';'.$medi.';'.$ruta.';'.$enva.';'.$incimas.';'.$segui;
?>